### ISSUE TITLE
建议增加“南七茶馆”以及请求转载

### ISSUE THREAD

**Issue by ZeQueen-X** [zzh1996/USTC-Network-Resources#10]
[南七茶馆](https://ustcforum.com)是中国科学技术大学本科学生于2021年五月底开始搭建运营的学生讨论论坛。在某种程度上弥补了现有的瀚海星云 BBS 的功能，方便校内学生使用和交流。
目前采用的是使用 @mail.ustc.edu.cn 后缀进行注册，故可以保证论坛内容以科大相关内容为主。
注：此网站由学生运营，与学校官方无关。

另：请求授予转载此篇文章至南七茶馆的权限，转载时将注明来源。

**Comment by zzh1996** [comment]
方便发一个 Pull Request 吗？
转载没问题。
