### ISSUE TITLE
外部资源可以加进来吗？

### ISSUE THREAD

**Issue by fengzhao** [zzh1996/USTC-Network-Resources#14]
比如，外部一些大厂的学生优惠，https://github.com/ivmm/Student-resources

**Comment by zzh1996** [comment]
原则上只收录校内的资源和学校主动购买的资源，而不收录这种所有学校通用的教育优惠。不过可以在文末加个链接，欢迎 PR

**Comment by zzh1996** [comment]
已添加链接
