### ISSUE TITLE
您好，请问可以帮忙下载一些资料吗？

### ISSUE THREAD

**Issue by fengzhao** [zzh1996/USTC-Network-Resources#18]
https://lib-ustc.wqxuetang.com/book/3201901  信息系统项目管理师教程（第3版）
https://lib-ustc.wqxuetang.com/book/3223032  信息系统项目管理师考试辅导（针对上午考试）
https://lib-ustc.wqxuetang.com/book/3215754   信息系统项目管理师考试辅导（针对下午案例与论文考试）

**Comment by zzh1996** [comment]
我们不提供代下载服务，请不要在 Issue 里面发与项目无关的内容
