### ISSUE TITLE
请问贵校的 matlab 是 server 吗，还是很多 licenses 呢

### ISSUE THREAD

**Issue by junyixu** [zzh1996/USTC-Network-Resources#2]

**Comment by zzh1996** [comment]
	校园版：适用于在校内使用并且可以连接到MATLAB授权服务器的用户。每次启动时都需要连接校内激活服务器验证进行激活，在校外使用时一般需要登录教工网络通自带的VPN后才可以连接到授权服务器激活。
	独立版：适用于无法连接校内授权服务器的电脑，激活时无需联网激活，但license有效期较短，到期后需要重新激活。
	机房版：适用于机房内部电脑无法连接学校授权服务器的情况，需要在用户机房内设置一台授权服务器，对内部电脑进行授权。
	MATLAB® Distributed Computing Server™32 pack需要单独申请安装。
