### ISSUE TITLE
网站部分建议删除一项；教育优惠部分建议增加一项

### ISSUE THREAD

**Issue by tageniu** [zzh1996/USTC-Network-Resources#8]
1. 网站部分的“202.141.162.24:7480（自助打印复印管理系统）”已过时，现已更换为“窝趣云打印”小程序，其官网网址也可以在小程序内找到，故应考虑删除此项；

2. 教育优惠部分建议增加一项“Office 365 教育版 A1 计划”，详见“https://ustcnet.ustc.edu.cn/2018/1219/c11104a366368/page.htm”和“http://staff.ustc.edu.cn/~wf0229/office365/”。个人认为这个 Office 365 Online 最有用的功能包括 Word 软件的编辑器（Editor）功能，可以用来给英文文章润色；以及 PowerPoint 软件的设计灵感（Design Ideas）功能，可以很快做出美观的ppt。

**Comment by zzh1996** [comment]
感谢建议，我最近比较忙，等我有空的时候加一下

**Comment by zzh1996** [comment]
改好了
