### ISSUE TITLE
教育网镜像站

### ISSUE THREAD

**Issue by woytu** [zzh1996/USTC-Network-Resources#9]
| 地区   	| 名称             	| IPv4 & IPv6                                                 	| IPv4                                                              	| IPv6                                                              	| GitHub                       	|
|--------	|------------------	|-------------------------------------------------------------	|-------------------------------------------------------------------	|-------------------------------------------------------------------	|------------------------------	|
| 东北   	| 东北大学         	| http://mirror.neu.edu.cn                                    	|                                                                   	|                                                                   	|                              	|
| 东北   	| 大连理工大学     	| http://mirror.dlut.edu.cn                                   	|                                                                   	|                                                                   	|                              	|
| 东北   	| 大连东软信息学院 	| http://mirrors.neusoft.edu.cn                               	|                                                                   	|                                                                   	|                              	|
| 东北   	| 哈尔滨工业大学   	| http://mirrors.hit.edu.cn                                   	|                                                                   	|                                                                   	| https://github.com/hitlug    	|
| 华北   	| 清华大学         	| https://mirrors.tuna.tsinghua.edu.cn                        	| https://mirrors4.tuna.tsinghua.edu.cn                             	| https://mirrors6.tuna.tsinghua.edu.cn                             	| https://github.com/tuna      	|
| 华北   	| 北京外国语大学   	| https://mirrors.bfsu.edu.cn                                 	| https://mirrors4.bfsu.edu.cn                                      	| https://mirrors6.bfsu.edu.cn                                      	|                              	|
| 华北   	| 北京理工大学     	|                                                             	|                                                                   	|                                                                   	|                              	|
| 华北   	| 北京交通大学     	| https://mirror.bjtu.edu.cn                                  	|                                                                   	|                                                                   	| https://github.com/bjtulug   	|
| 华北   	| 天津大学         	|                                                             	|                                                                   	|                                                                   	|                              	|
| 华东北 	| 中国科学技术大学 	| http://mirrors.ustc.edu.cn      https://mirrors.ustc.edu.cn 	| http://mirrors4.ustc.edu.cn      https://ipv4.mirrors.ustc.edu.cn 	| http://mirrors6.ustc.edu.cn      https://ipv6.mirrors.ustc.edu.cn 	| https://github.com/ustclug   	|
| 华中   	| 华中科技大学     	|                                                             	| http://mirrors.hust.edu.cn                                        	|                                                                   	|                              	|
| 华中   	| 中国地质大学     	|                                                             	|                                                                   	|                                                                   	|                              	|
| 华东南 	| 上海交通大学     	|                                                             	| http://ftp.sjtu.edu.cn                                            	|                                                                   	|                              	|
| 华东南 	| 浙江大学         	| http://mirrors.zju.edu.cn                                   	|                                                                   	|                                                                   	|                              	|
| 华东南 	| 厦门大学         	|                                                             	|                                                                   	|                                                                   	|                              	|
| 华南   	| 中山大学         	|                                                             	|                                                                   	|                                                                   	|                              	|
| 西北   	| 兰州大学         	| http://mirror.lzu.edu.cn                                    	|                                                                   	|                                                                   	| https://github.com/LZUOSS    	|
| 西南   	| 重庆大学         	|                                                             	| https://mirrors.cqu.edu.cn                                        	|                                                                   	| https://github.com/cqumirror 	|

**Comment by zzh1996** [comment]
这个项目不收录教育网通用的资源，只收录跟本校有关的
